import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// CLERK
import { ClerkProvider } from '@clerk/nextjs';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/next.svg',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(inter.className, 'subpixel-antialiased')}>
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
